### ISSUE TITLE
Set outfilesuffix and relfileprefix attributes in configuration

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#200]
Set the following two attributes in the configuration to make interdocument references work with the Awestruct Indexifier extension.

```
asciidoctor:
  :attributes:
    relfileprefix: '../'
    outfilesuffix: '/'
```
